# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stackedWidget.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.signInUpPage_widget = QtWidgets.QWidget()
        self.signInUpPage_widget.setObjectName("signInUpPage_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.signInUpPage_widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.signInUp_widget = QtWidgets.QWidget(self.signInUpPage_widget)
        self.signInUp_widget.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.signInUp_widget.setObjectName("signInUp_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.signInUp_widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.signInUp_stackedWidget = QtWidgets.QStackedWidget(self.signInUp_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.signInUp_stackedWidget.sizePolicy().hasHeightForWidth())
        self.signInUp_stackedWidget.setSizePolicy(sizePolicy)
        self.signInUp_stackedWidget.setMinimumSize(QtCore.QSize(320, 420))
        self.signInUp_stackedWidget.setObjectName("signInUp_stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setMinimumSize(QtCore.QSize(320, 220))
        self.widget_2.setMaximumSize(QtCore.QSize(320, 220))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout_2.addWidget(self.username_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout_2.addWidget(self.password_lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.signIn_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.signIn_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.signIn_pushButton.setFont(font)
        self.signIn_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.signIn_pushButton.setAutoDefault(False)
        self.signIn_pushButton.setDefault(False)
        self.signIn_pushButton.setFlat(False)
        self.signIn_pushButton.setObjectName("signIn_pushButton")
        self.verticalLayout_2.addWidget(self.signIn_pushButton)
        self.openSignUpPage_pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSignUpPage_pushButton.sizePolicy().hasHeightForWidth())
        self.openSignUpPage_pushButton.setSizePolicy(sizePolicy)
        self.openSignUpPage_pushButton.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        self.openSignUpPage_pushButton.setFont(font)
        self.openSignUpPage_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.openSignUpPage_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.openSignUpPage_pushButton.setAutoDefault(False)
        self.openSignUpPage_pushButton.setDefault(False)
        self.openSignUpPage_pushButton.setFlat(False)
        self.openSignUpPage_pushButton.setObjectName("openSignUpPage_pushButton")
        self.verticalLayout_2.addWidget(self.openSignUpPage_pushButton)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.signInUp_stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setMinimumSize(QtCore.QSize(320, 430))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.firstname_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.firstname_lineEdit.setFont(font)
        self.firstname_lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.firstname_lineEdit.setObjectName("firstname_lineEdit")
        self.verticalLayout_4.addWidget(self.firstname_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lastname_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.lastname_lineEdit.setFont(font)
        self.lastname_lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.lastname_lineEdit.setObjectName("lastname_lineEdit")
        self.verticalLayout_4.addWidget(self.lastname_lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.username_lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.username_lineEdit_2.setFont(font)
        self.username_lineEdit_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.username_lineEdit_2.setObjectName("username_lineEdit_2")
        self.verticalLayout_4.addWidget(self.username_lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.password_lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.password_lineEdit_2.setFont(font)
        self.password_lineEdit_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.password_lineEdit_2.setText("")
        self.password_lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit_2.setObjectName("password_lineEdit_2")
        self.verticalLayout_4.addWidget(self.password_lineEdit_2)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.repeatPassword_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.repeatPassword_lineEdit.setFont(font)
        self.repeatPassword_lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.repeatPassword_lineEdit.setText("")
        self.repeatPassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeatPassword_lineEdit.setObjectName("repeatPassword_lineEdit")
        self.verticalLayout_4.addWidget(self.repeatPassword_lineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.register_pushButton = QtWidgets.QPushButton(self.widget_3)
        self.register_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.register_pushButton.setAutoDefault(False)
        self.register_pushButton.setDefault(False)
        self.register_pushButton.setFlat(False)
        self.register_pushButton.setObjectName("register_pushButton")
        self.verticalLayout_4.addWidget(self.register_pushButton)
        self.openSignInPage_pushButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSignInPage_pushButton.sizePolicy().hasHeightForWidth())
        self.openSignInPage_pushButton.setSizePolicy(sizePolicy)
        self.openSignInPage_pushButton.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        self.openSignInPage_pushButton.setFont(font)
        self.openSignInPage_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.openSignInPage_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.openSignInPage_pushButton.setAutoDefault(False)
        self.openSignInPage_pushButton.setDefault(False)
        self.openSignInPage_pushButton.setFlat(False)
        self.openSignInPage_pushButton.setObjectName("openSignInPage_pushButton")
        self.verticalLayout_4.addWidget(self.openSignInPage_pushButton)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.signInUp_stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.signInUp_stackedWidget, 2, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.signInUp_widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.signInOutSettings_pushButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signInOutSettings_pushButton.sizePolicy().hasHeightForWidth())
        self.signInOutSettings_pushButton.setSizePolicy(sizePolicy)
        self.signInOutSettings_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.signInOutSettings_pushButton.setFont(font)
        self.signInOutSettings_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.signInOutSettings_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"QAbstractButton{\n"
"    icon: url(resources/images/settings_default_100px.png);\n"
"}\n"
"QAbstractButton:hover{\n"
"    icon: url(resources/images/settings_hovered_100px.png);\n"
"}\n"
"QAbstractButton:pressed{\n"
"    icon: url(resources/images/settings_pressed_100px.png);\n"
"}")
        self.signInOutSettings_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/settings_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signInOutSettings_pushButton.setIcon(icon)
        self.signInOutSettings_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.signInOutSettings_pushButton.setAutoDefault(False)
        self.signInOutSettings_pushButton.setDefault(False)
        self.signInOutSettings_pushButton.setFlat(False)
        self.signInOutSettings_pushButton.setObjectName("signInOutSettings_pushButton")
        self.gridLayout_2.addWidget(self.signInOutSettings_pushButton, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 3, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.signInUp_widget)
        self.stackedWidget.addWidget(self.signInUpPage_widget)
        self.mainPage_widget = QtWidgets.QWidget()
        self.mainPage_widget.setObjectName("mainPage_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainPage_widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.main_widget = QtWidgets.QWidget(self.mainPage_widget)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuPanel_widget = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuPanel_widget.sizePolicy().hasHeightForWidth())
        self.menuPanel_widget.setSizePolicy(sizePolicy)
        self.menuPanel_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.menuPanel_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menuPanel_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuPanel_widget.setStyleSheet("QWidget#menuPanel_widget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-top-left-radius: 20px;\n"
"    margin-top: 15px;\n"
"}")
        self.menuPanel_widget.setObjectName("menuPanel_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.menuPanel_widget)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(0, 15, 0, 10)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.temp_home_pushButton = QtWidgets.QPushButton(self.menuPanel_widget)
        self.temp_home_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_home_pushButton.sizePolicy().hasHeightForWidth())
        self.temp_home_pushButton.setSizePolicy(sizePolicy)
        self.temp_home_pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.temp_home_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.temp_home_pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.temp_home_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.temp_home_pushButton.setFont(font)
        self.temp_home_pushButton.setMouseTracking(True)
        self.temp_home_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp_home_pushButton.setStyleSheet("QPushButton{\n"
"           /*outline*/\n"
"            outline: 0;\n"
"            /*outline-end*/\n"
"            /*border*/\n"
"            border: none;\n"
"            border-radius: 0px;\n"
"            border-top-left-radius: 10px;\n"
"            border-top-right-radius: 10px;\n"
"            border-bottom-right-radius: 0px;\n"
"            /*border-end*/\n"
"            /*background-color*/\n"
"            background-color:rgba(50, 50, 50, 255);\n"
"            /*background-color-end*/\n"
"            /*color*/\n"
"            color: rgb(255, 255, 255);\n"
"            /*color-end*/\n"
"            /*padding*/\n"
"            padding: 10px;\n"
"            /*padding-end*/\n"
"            /*margin*/\n"
"            margin: 0px;\n"
"            /*margin-end*/\n"
"            /*margin-right*/\n"
"            margin-right: 0px;\n"
"            /*margin-right-end*/\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/images/home_hovered_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temp_home_pushButton.setIcon(icon1)
        self.temp_home_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.temp_home_pushButton.setCheckable(False)
        self.temp_home_pushButton.setAutoDefault(False)
        self.temp_home_pushButton.setDefault(False)
        self.temp_home_pushButton.setFlat(False)
        self.temp_home_pushButton.setObjectName("temp_home_pushButton")
        self.verticalLayout_8.addWidget(self.temp_home_pushButton)
        self.temp_stats_pushButton = QtWidgets.QPushButton(self.menuPanel_widget)
        self.temp_stats_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_stats_pushButton.sizePolicy().hasHeightForWidth())
        self.temp_stats_pushButton.setSizePolicy(sizePolicy)
        self.temp_stats_pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.temp_stats_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.temp_stats_pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.temp_stats_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.temp_stats_pushButton.setFont(font)
        self.temp_stats_pushButton.setMouseTracking(True)
        self.temp_stats_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp_stats_pushButton.setStyleSheet("QPushButton{\n"
"           /*outline*/\n"
"            outline: 0;\n"
"            /*outline-end*/\n"
"            /*border*/\n"
"            border: none;\n"
"            border-radius: 0px;\n"
"            border-top-right-radius: 0px;\n"
"            border-bottom-right-radius: 0px;\n"
"            /*border-end*/\n"
"            /*background-color*/\n"
"            background-color:rgba(50, 50, 50, 255);\n"
"            /*background-color-end*/\n"
"            /*color*/\n"
"            color: rgb(255, 255, 255);\n"
"            /*color-end*/\n"
"            /*padding*/\n"
"            padding: 10px;\n"
"            /*padding-end*/\n"
"            /*margin*/\n"
"            margin: 0px;\n"
"            /*margin-end*/\n"
"            /*margin-right*/\n"
"            margin-right: 0px;\n"
"            /*margin-right-end*/\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/images/combo_chart_filled_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temp_stats_pushButton.setIcon(icon2)
        self.temp_stats_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.temp_stats_pushButton.setCheckable(False)
        self.temp_stats_pushButton.setAutoDefault(False)
        self.temp_stats_pushButton.setDefault(False)
        self.temp_stats_pushButton.setFlat(False)
        self.temp_stats_pushButton.setObjectName("temp_stats_pushButton")
        self.verticalLayout_8.addWidget(self.temp_stats_pushButton)
        self.temp_schedule_pushButton = QtWidgets.QPushButton(self.menuPanel_widget)
        self.temp_schedule_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_schedule_pushButton.sizePolicy().hasHeightForWidth())
        self.temp_schedule_pushButton.setSizePolicy(sizePolicy)
        self.temp_schedule_pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.temp_schedule_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.temp_schedule_pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.temp_schedule_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.temp_schedule_pushButton.setFont(font)
        self.temp_schedule_pushButton.setMouseTracking(True)
        self.temp_schedule_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp_schedule_pushButton.setStyleSheet("QPushButton{\n"
"            /*outline*/\n"
"            outline: 0;\n"
"            /*outline-end*/\n"
"            /*border*/\n"
"            border: none;\n"
"            border-radius: 0px;\n"
"            border-top-right-radius: 0px;\n"
"            border-bottom-right-radius: 0px;\n"
"            /*border-end*/\n"
"            /*background-color*/\n"
"            background-color:rgba(50, 50, 50, 255);\n"
"            /*background-color-end*/\n"
"            /*color*/\n"
"            color: rgb(255, 255, 255);\n"
"            /*color-end*/\n"
"            /*padding*/\n"
"            padding: 10px;\n"
"            /*padding-end*/\n"
"            /*margin*/\n"
"            margin: 0px;\n"
"            /*margin-end*/\n"
"            /*margin-right*/\n"
"            margin-right: 0px;\n"
"            /*margin-right-end*/\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/images/schedule_100px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temp_schedule_pushButton.setIcon(icon3)
        self.temp_schedule_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.temp_schedule_pushButton.setCheckable(False)
        self.temp_schedule_pushButton.setAutoDefault(False)
        self.temp_schedule_pushButton.setDefault(False)
        self.temp_schedule_pushButton.setFlat(False)
        self.temp_schedule_pushButton.setObjectName("temp_schedule_pushButton")
        self.verticalLayout_8.addWidget(self.temp_schedule_pushButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.temp_menuSignOut_pushButton = QtWidgets.QPushButton(self.menuPanel_widget)
        self.temp_menuSignOut_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_menuSignOut_pushButton.sizePolicy().hasHeightForWidth())
        self.temp_menuSignOut_pushButton.setSizePolicy(sizePolicy)
        self.temp_menuSignOut_pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.temp_menuSignOut_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.temp_menuSignOut_pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.temp_menuSignOut_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.temp_menuSignOut_pushButton.setFont(font)
        self.temp_menuSignOut_pushButton.setMouseTracking(True)
        self.temp_menuSignOut_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp_menuSignOut_pushButton.setStyleSheet("QPushButton{\n"
"            /*outline*/\n"
"            outline: 0;\n"
"            /*outline-end*/\n"
"            /*border*/\n"
"            border: none;\n"
"            border-radius: 0px;\n"
"            border-top-right-radius: 0px;\n"
"            border-bottom-right-radius: 0px;\n"
"            /*border-end*/\n"
"            /*background-color*/\n"
"            background-color:rgba(50, 50, 50, 255);\n"
"            /*background-color-end*/\n"
"            /*color*/\n"
"            color: rgb(255, 255, 255);\n"
"            /*color-end*/\n"
"            /*padding*/\n"
"            padding: 10px;\n"
"            /*padding-end*/\n"
"            /*margin*/\n"
"            margin: 0px;\n"
"            /*margin-end*/\n"
"            /*margin-right*/\n"
"            margin-right: 0px;\n"
"            /*margin-right-end*/\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/images/icons8-logout-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.temp_menuSignOut_pushButton.setIcon(icon4)
        self.temp_menuSignOut_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.temp_menuSignOut_pushButton.setCheckable(False)
        self.temp_menuSignOut_pushButton.setAutoDefault(False)
        self.temp_menuSignOut_pushButton.setDefault(False)
        self.temp_menuSignOut_pushButton.setFlat(False)
        self.temp_menuSignOut_pushButton.setObjectName("temp_menuSignOut_pushButton")
        self.verticalLayout_8.addWidget(self.temp_menuSignOut_pushButton)
        self.horizontalLayout.addWidget(self.menuPanel_widget)
        self.mainPanel_widget = QtWidgets.QWidget(self.main_widget)
        self.mainPanel_widget.setStyleSheet("QWidget#mainPanel_widget{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-radius: 0px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    margin-bottom: 15px;\n"
"}")
        self.mainPanel_widget.setObjectName("mainPanel_widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mainPanel_widget)
        self.verticalLayout_9.setContentsMargins(20, 20, 20, 30)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mainPanel_stackedWidget = QtWidgets.QStackedWidget(self.mainPanel_widget)
        self.mainPanel_stackedWidget.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.mainPanel_stackedWidget.setObjectName("mainPanel_stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.newsPanel_widget = QtWidgets.QWidget(self.page_3)
        self.newsPanel_widget.setMinimumSize(QtCore.QSize(300, 0))
        self.newsPanel_widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.newsPanel_widget.setStyleSheet("QWidget#newsPanel_widget{\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 20px;\n"
"}")
        self.newsPanel_widget.setObjectName("newsPanel_widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.newsPanel_widget)
        self.verticalLayout_10.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget = QtWidgets.QWidget(self.newsPanel_widget)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setStyleSheet("border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"margin-right: 20px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.verticalLayout_10.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(self.newsPanel_widget)
        self.widget_5.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border: none;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_11.setContentsMargins(20, 20, 0, 20)
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_5)
        self.scrollArea.setStyleSheet("QScrollBar\n"
"{\n"
"    border: none;\n"
"    background-image: none;\n"
"    background-color: rgb(0, 0,0);\n"
"    background: rgb(0, 0,0);\n"
"    foreground-color: rgb(0, 0,0);\n"
"    foreground: rgb(0, 0,0);\n"
"    color: rgb(0, 0, 0);\n"
"    width: 10px;\n"
"}\n"
"QScrollBar::handle\n"
"{\n"
"    background : rgb(60, 60, 60);\n"
"}\n"
"QScrollBar::handle::pressed\n"
"{\n"
"    background : rgb(30, 30, 30);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 463, 998))
        self.scrollAreaWidgetContents.setStyleSheet("border: none;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_12.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        self.widget_7.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_7.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_7.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setMinimumSize(QtCore.QSize(30, 30))
        self.label_9.setMaximumSize(QtCore.QSize(30, 30))
        self.label_9.setStyleSheet("border-radius: 20px;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_3.addWidget(self.widget_10)
        self.verticalLayout_12.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.verticalLayout_12.addWidget(self.widget_9)
        self.verticalLayout_15.addWidget(self.widget_6)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_16.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_13.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_13.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.widget_13)
        self.label_13.setMinimumSize(QtCore.QSize(30, 30))
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setStyleSheet("border-radius: 20px;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15)
        self.horizontalLayout_4.addWidget(self.widget_14)
        self.verticalLayout_16.addWidget(self.widget_12)
        self.widget_15 = QtWidgets.QWidget(self.widget_11)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_18.addWidget(self.label_16)
        self.verticalLayout_16.addWidget(self.widget_15)
        self.verticalLayout_15.addWidget(self.widget_11)
        self.widget_49 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_49.sizePolicy().hasHeightForWidth())
        self.widget_49.setSizePolicy(sizePolicy)
        self.widget_49.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_49.setObjectName("widget_49")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.widget_49)
        self.verticalLayout_40.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_40.setSpacing(0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.widget_50 = QtWidgets.QWidget(self.widget_49)
        self.widget_50.setObjectName("widget_50")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_50)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_51 = QtWidgets.QWidget(self.widget_50)
        self.widget_51.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_51.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_51.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_51.setObjectName("widget_51")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_51)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_45 = QtWidgets.QLabel(self.widget_51)
        self.label_45.setMinimumSize(QtCore.QSize(30, 30))
        self.label_45.setMaximumSize(QtCore.QSize(30, 30))
        self.label_45.setStyleSheet("border-radius: 20px;")
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.widget_51)
        self.widget_52 = QtWidgets.QWidget(self.widget_50)
        self.widget_52.setObjectName("widget_52")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.widget_52)
        self.verticalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_41.setSpacing(5)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_46 = QtWidgets.QLabel(self.widget_52)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_41.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.widget_52)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_47.setObjectName("label_47")
        self.verticalLayout_41.addWidget(self.label_47)
        self.horizontalLayout_12.addWidget(self.widget_52)
        self.verticalLayout_40.addWidget(self.widget_50)
        self.widget_53 = QtWidgets.QWidget(self.widget_49)
        self.widget_53.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_53.setObjectName("widget_53")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.widget_53)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_48 = QtWidgets.QLabel(self.widget_53)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_48.setTextFormat(QtCore.Qt.RichText)
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_42.addWidget(self.label_48)
        self.verticalLayout_40.addWidget(self.widget_53)
        self.verticalLayout_15.addWidget(self.widget_49)
        self.widget_44 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_44.sizePolicy().hasHeightForWidth())
        self.widget_44.setSizePolicy(sizePolicy)
        self.widget_44.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_44.setObjectName("widget_44")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.widget_44)
        self.verticalLayout_37.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.widget_45 = QtWidgets.QWidget(self.widget_44)
        self.widget_45.setObjectName("widget_45")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_45)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_46 = QtWidgets.QWidget(self.widget_45)
        self.widget_46.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_46.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_46.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_46.setObjectName("widget_46")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_46)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_41 = QtWidgets.QLabel(self.widget_46)
        self.label_41.setMinimumSize(QtCore.QSize(30, 30))
        self.label_41.setMaximumSize(QtCore.QSize(30, 30))
        self.label_41.setStyleSheet("border-radius: 20px;")
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.widget_46)
        self.widget_47 = QtWidgets.QWidget(self.widget_45)
        self.widget_47.setObjectName("widget_47")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.widget_47)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(5)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_42 = QtWidgets.QLabel(self.widget_47)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_38.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.widget_47)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_38.addWidget(self.label_43)
        self.horizontalLayout_11.addWidget(self.widget_47)
        self.verticalLayout_37.addWidget(self.widget_45)
        self.widget_48 = QtWidgets.QWidget(self.widget_44)
        self.widget_48.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_48.setObjectName("widget_48")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.widget_48)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_44 = QtWidgets.QLabel(self.widget_48)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_44.setTextFormat(QtCore.Qt.RichText)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_39.addWidget(self.label_44)
        self.verticalLayout_37.addWidget(self.widget_48)
        self.verticalLayout_15.addWidget(self.widget_44)
        self.widget_39 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_39.sizePolicy().hasHeightForWidth())
        self.widget_39.setSizePolicy(sizePolicy)
        self.widget_39.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_39.setObjectName("widget_39")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.widget_39)
        self.verticalLayout_34.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.widget_40 = QtWidgets.QWidget(self.widget_39)
        self.widget_40.setObjectName("widget_40")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_40)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_41 = QtWidgets.QWidget(self.widget_40)
        self.widget_41.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_41.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_41.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_41.setObjectName("widget_41")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_41)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_37 = QtWidgets.QLabel(self.widget_41)
        self.label_37.setMinimumSize(QtCore.QSize(30, 30))
        self.label_37.setMaximumSize(QtCore.QSize(30, 30))
        self.label_37.setStyleSheet("border-radius: 20px;")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.widget_41)
        self.widget_42 = QtWidgets.QWidget(self.widget_40)
        self.widget_42.setObjectName("widget_42")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.widget_42)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(5)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_38 = QtWidgets.QLabel(self.widget_42)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_35.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.widget_42)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_35.addWidget(self.label_39)
        self.horizontalLayout_10.addWidget(self.widget_42)
        self.verticalLayout_34.addWidget(self.widget_40)
        self.widget_43 = QtWidgets.QWidget(self.widget_39)
        self.widget_43.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_43.setObjectName("widget_43")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.widget_43)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_40 = QtWidgets.QLabel(self.widget_43)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_40.setTextFormat(QtCore.Qt.RichText)
        self.label_40.setWordWrap(True)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_36.addWidget(self.label_40)
        self.verticalLayout_34.addWidget(self.widget_43)
        self.verticalLayout_15.addWidget(self.widget_39)
        self.widget_21 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_21.sizePolicy().hasHeightForWidth())
        self.widget_21.setSizePolicy(sizePolicy)
        self.widget_21.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_28.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.widget_30 = QtWidgets.QWidget(self.widget_21)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_31 = QtWidgets.QWidget(self.widget_30)
        self.widget_31.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_31.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_31.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_31.setObjectName("widget_31")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_31)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_29 = QtWidgets.QLabel(self.widget_31)
        self.label_29.setMinimumSize(QtCore.QSize(30, 30))
        self.label_29.setMaximumSize(QtCore.QSize(30, 30))
        self.label_29.setStyleSheet("border-radius: 20px;")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.widget_31)
        self.widget_32 = QtWidgets.QWidget(self.widget_30)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.widget_32)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(5)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_30 = QtWidgets.QLabel(self.widget_32)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_29.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.widget_32)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_29.addWidget(self.label_31)
        self.horizontalLayout_8.addWidget(self.widget_32)
        self.verticalLayout_28.addWidget(self.widget_30)
        self.widget_33 = QtWidgets.QWidget(self.widget_21)
        self.widget_33.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_33)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_32 = QtWidgets.QLabel(self.widget_33)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setTextFormat(QtCore.Qt.RichText)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_30.addWidget(self.label_32)
        self.verticalLayout_28.addWidget(self.widget_33)
        self.verticalLayout_15.addWidget(self.widget_21)
        self.widget_34 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_34.sizePolicy().hasHeightForWidth())
        self.widget_34.setSizePolicy(sizePolicy)
        self.widget_34.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_34.setObjectName("widget_34")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.widget_34)
        self.verticalLayout_31.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.widget_35 = QtWidgets.QWidget(self.widget_34)
        self.widget_35.setObjectName("widget_35")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_35)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_36 = QtWidgets.QWidget(self.widget_35)
        self.widget_36.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_36.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_36.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_36.setObjectName("widget_36")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_36)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_33 = QtWidgets.QLabel(self.widget_36)
        self.label_33.setMinimumSize(QtCore.QSize(30, 30))
        self.label_33.setMaximumSize(QtCore.QSize(30, 30))
        self.label_33.setStyleSheet("border-radius: 20px;")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.widget_36)
        self.widget_37 = QtWidgets.QWidget(self.widget_35)
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.widget_37)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_34 = QtWidgets.QLabel(self.widget_37)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_32.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.widget_37)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_32.addWidget(self.label_35)
        self.horizontalLayout_9.addWidget(self.widget_37)
        self.verticalLayout_31.addWidget(self.widget_35)
        self.widget_38 = QtWidgets.QWidget(self.widget_34)
        self.widget_38.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_38.setObjectName("widget_38")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.widget_38)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_36 = QtWidgets.QLabel(self.widget_38)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_36.setTextFormat(QtCore.Qt.RichText)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_33.addWidget(self.label_36)
        self.verticalLayout_31.addWidget(self.widget_38)
        self.verticalLayout_15.addWidget(self.widget_34)
        self.widget_16 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_19.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setMinimumSize(QtCore.QSize(40, 40))
        self.widget_18.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_18.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 20px;")
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_18)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_17 = QtWidgets.QLabel(self.widget_18)
        self.label_17.setMinimumSize(QtCore.QSize(30, 30))
        self.label_17.setMaximumSize(QtCore.QSize(30, 30))
        self.label_17.setStyleSheet("border-radius: 20px;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("resources/images/icons8-female-user-100.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.widget_17)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_18 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_20.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_20.addWidget(self.label_19)
        self.horizontalLayout_5.addWidget(self.widget_19)
        self.verticalLayout_19.addWidget(self.widget_17)
        self.widget_20 = QtWidgets.QWidget(self.widget_16)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setTextFormat(QtCore.Qt.RichText)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_21.addWidget(self.label_20)
        self.verticalLayout_19.addWidget(self.widget_20)
        self.verticalLayout_15.addWidget(self.widget_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.gridLayout_3.addWidget(self.newsPanel_widget, 1, 0, 2, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.mainPanel_stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.mainPanel_stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.mainPanel_stackedWidget.addWidget(self.page_5)
        self.verticalLayout_9.addWidget(self.mainPanel_stackedWidget)
        self.horizontalLayout.addWidget(self.mainPanel_widget)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_7.addWidget(self.main_widget)
        self.stackedWidget.addWidget(self.mainPage_widget)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.signInUp_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.signIn_pushButton.setText(_translate("MainWindow", "Sign in"))
        self.openSignUpPage_pushButton.setText(_translate("MainWindow", "Sign up?"))
        self.label_6.setText(_translate("MainWindow", "Firstname*"))
        self.label_5.setText(_translate("MainWindow", "Lastname*"))
        self.label_3.setText(_translate("MainWindow", "Username*"))
        self.label_4.setText(_translate("MainWindow", "Password*"))
        self.label_7.setText(_translate("MainWindow", "Repeat Password*"))
        self.register_pushButton.setText(_translate("MainWindow", "Register"))
        self.openSignInPage_pushButton.setText(_translate("MainWindow", "Sign in?"))
        self.temp_home_pushButton.setText(_translate("MainWindow", "Home"))
        self.temp_stats_pushButton.setText(_translate("MainWindow", "Stats"))
        self.temp_schedule_pushButton.setText(_translate("MainWindow", "Schedule"))
        self.temp_menuSignOut_pushButton.setText(_translate("MainWindow", "Sign out"))
        self.label_8.setText(_translate("MainWindow", "Feed (FA-Stufe)"))
        self.label_10.setText(_translate("MainWindow", "Julia M."))
        self.label_12.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Julia M."))
        self.label_15.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "Julia M."))
        self.label_47.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "Julia M."))
        self.label_43.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "Julia M."))
        self.label_39.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "Julia M."))
        self.label_31.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "Julia M."))
        self.label_35.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Julia M."))
        self.label_19.setText(_translate("MainWindow", "12:31 - Friday"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Die Räume in der <span style=\" font-weight:600;\">3.Etage</span> zu den FA-Räumen sind in renovierung, bitte frühzeitig umbuchen.</p></body></html>"))
